apps/app_one/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
# from root route to index method
    url(r'^$', views.index),
    url(r'index^$', views.index, name="index"),
    url(r'^post_message$', views.post_message, name="post_message"),
    # url(r'^post_comment$', views.post_comment, name="post_comment"),
    url(r'^post_comment/(?P<ms_id>\d+)$', views.post_comment, name="post_comment"),
    url(r'^logoff$', views.logoff, name="logoff"),
]

the_wall/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.app_one.urls', namespace="app_one")),
    # url(r'^admin/', admin.site.urls),
]

apps/app_one/models.py
from django.db import models
from datetime import datetime, date

# Create your models here.
class User(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


# this is the database where messages will be stored
# many messages, one user
class Message(models.Model):
    user_id = models.ForeignKey(User, related_name="messages")
    message = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


# this is the database where comments on the messages will be stored
# many comments, many messages
# many comments, one user
class Comment(models.Model):
    message_id = models.ForeignKey(Message, related_name="comments", null=True)
    user_id = models.ForeignKey(User, related_name="comments")
    comment = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

apps/app_one/views.py
from django.shortcuts import render, HttpResponse, redirect
from .models import User, Message, Comment


# Create your views here.
def index(request):
    print("This is index method in views.py")
    context = {
        # 'users': User.objects.filter(id=2),
        'users': User.objects.all(),
        # 'messages': Message.objects.filter(user_id=2),
        # 'messages': Message.objects.all(),
    }
    # users=User.objects.all()
    # print(users[0].messages)
    return render(request, 'app_one/index.html', context)


def post_message(request):
    print("This is post_message method in views.py")

    if request.method == "POST":
        print("POST, messages")
        new_message = request.POST['message']
        print("Message is:", new_message)

        this_user = User.objects.get(id=4)
        print(this_user.id, this_user.first_name, this_user.last_name, this_user.email)

        # user = request.session.this_user
        # print("Session user is:", user.first_name)

        saved_message = Message.objects.create(user_id=this_user, message=new_message)
        print(saved_message)

        return redirect('app_one:post_message')
    return redirect('/')


def post_comment(request, ms_id):
    print("This is post_comment method in views.py")

    if request.method == "POST":
        print("POST, comments")
        print(ms_id)
        ms_id = int(ms_id)
        new_comment = request.POST['comment']
        print("Comment is:", new_comment)

        this_user = User.objects.get(id=4)
        print(this_user.id, this_user.first_name, this_user.last_name, this_user.email)

        this_message = Message.objects.get(id=ms_id)

# creating Comment object
        saved_comment = Comment.objects.create(user_id=this_user, message_id=this_message, comment=new_comment)
        print(saved_comment)

    return redirect('/')


# nonfunctional; for logoff button on html
def logoff(request):
    print("This is logoff method in views.py")
    return redirect('/')

apps/app_one/templates/app_one/hold.html
<form class="commentbox" action="{% url 'app_one:post_comment' %}" method="POST" id="send_comment">
  {% csrf_token %}
  <textarea name="comment" rows="4" cols="60" value={{ message.id }}>{{ message.id }}</textarea>
  <button type="submit" form="send_comment" value="">Post a comment</button>
</form>

apps/app_one/templates/app_one/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'app_one/css/style.css' %}" media="screen" title="no title">
    <title>Index page</title>
  </head>

  <body>
    <div class="wrapper">

      <div class="header">
        <!-- this project doesn't have login/registration, so user.first_name isn't in session and therefore won't appear at top of home page  -->
        <!-- the 2 test users were entered into the db via shell commands -->
        <!-- logoff button nonfunctional here -->
        <h1 class="ele_line">CodingDojo Wall</h1>Welcome, {{ user.first_name }}<a href={% url 'app_one:logoff' %}>log off</a>
      </div>

      <h2>Post a message</h2>

      <form class="messagebox" action="{% url 'app_one:post_message'%}" method="POST" id="send_message">
        {% csrf_token %}
        <textarea name ="message" rows="5" cols="80" value=""></textarea>
        <button type="submit" form="send_message" value="">Post a message</button>
      </form>

      {% for user in users %}

  <!-- 'messages' in user.messages refers to the related name in the Message model-->
        {% for message in user.messages.all %}

          <h5>{{ user.first_name }} {{ user.last_name }} {{ message.created_at }}</h5>
          <h5>{{ message.message }}</h5>


  <!-- displaying Comment objects -->
          <div class="comments">
            {% for comment in message.comments.all %}
              <p>{{ comment.user_id.first_name }} {{ comment.user_id.last_name }} {{ comment.created_at }}</p>
              <p>{{ comment.comment }}</p>
            {% endfor %} <!-- end of comment loop -->
          </div>

      <!-- comments here -->
      <!-- hidden field for message id? -->
          <form class="commentbox" action="{% url 'app_one:post_comment' ms_id=message.id %}" method="POST" id="send_comment">
            {% csrf_token %}
            <textarea name="comment" rows="4" cols="60" value="{{ message.id }}"></textarea>
            <button type="submit" form="send_comment" value="">Post a comment</button>
          </form>

        {% endfor %} <!-- end of messages loop -->

      {% endfor %} <!-- end of user loop -->

    </div> <!-- wrapper end div -->

  </body>
</html>